name = "admin-api-worker"
main = "build/index.js"
compatibility_date = "2024-09-01"

routes = [
  { pattern = "api.zygodactylstudios.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "zygo-cms-db"
database_id = "ba933697-e439-478d-b609-f8ba1feb264c"
migrations_dir = "../../migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "zygo-cms-media"

[vars]
ENVIRONMENT = "production"
EDGE_TTL_SECONDS = "86400"
PUBLIC_SUBDOMAIN = "www"

[triggers]
crons = ["0 0 * * SUN", "0 * * * *"]
