name = "public-worker"
main = "build/index.js"
compatibility_date = "2024-09-01"

routes = [
  { pattern = "zygodactylstudios.com", custom_domain = true },
  { pattern = "www.zygodactylstudios.com", custom_domain = true }
]

[assets]
directory = "../../public"

[[d1_databases]]
binding = "DB"
database_name = "zygo-cms-db"
database_id = "488417e7-4ad1-4875-90e9-71a0ac3dbc63"
migrations_dir = "../../migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "zygo-cms-media"

[vars]
EDGE_TTL_SECONDS = "86400"

[triggers]
crons = ["0 0 * * SUN", "0 * * * *"]
